name: Deployment

permissions:
  actions: read
  contents: read

on:
  workflow_run:
    workflows: ["Development"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Vercel
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-${{ github.event.workflow_run.head_branch }}
      cancel-in-progress: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Vercel Deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token:      ${{ secrets.VERCEL_TOKEN }}
          github-token:      ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id:     ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args:       ${{ github.event.workflow_run.head_branch == 'main' && '--prod' || }}
          github-comment:    ${{ github.event.workflow_run.head_branch != 'main' }}
