name: Preview Deployment

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  deployments: write
  pull-requests: write
  issues: write

env:
  VERCEL_ORG_ID:     ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN:      ${{ secrets.VERCEL_TOKEN }}

jobs:
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest

    environment:
      name: Preview
    
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install --global pnpm@latest

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token="$VERCEL_TOKEN"

      - name: Build Project Artifacts
        run: vercel build --token="$VERCEL_TOKEN"

      - name: Deploy to Vercel Preview (with debug)
        id: vercel-deploy
        run: |
          VERCEL_LOG=$(
            vercel deploy --yes --token="$VERCEL_TOKEN" 2>&1
          )
            
          echo "--------------------- Vercel CLI raw output ---------------------"
          echo "$VERCEL_LOG"
          echo "------------------------------------------------------------------"
      
          PREVIEW_URL=$(
            echo "$VERCEL_LOG" \
              | grep -E '^[[:space:]]*Preview:' \
              | awk '{print $2}'
          )
      
          echo ">>> Parsed PREVIEW_URL = '$PREVIEW_URL'"
      
          echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT

      - name: Comment PR with Preview URL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Preview is live: ${{ steps.vercel-deploy.outputs.preview_url }}`
            })
