name: Preview Deployment

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  deployments: write

env:
  VERCEL_ORG_ID:     ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN:      ${{ secrets.VERCEL_TOKEN }}

jobs:
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest

    environment:
      name: Preview
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.workflow_run.pull_requests[0].number }}/merge

      - name: Install pnpm
        run: npm install --global pnpm@latest

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token="$VERCEL_TOKEN"

      - name: Build Project Artifacts
        run: vercel build --token="$VERCEL_TOKEN"

      - name: Deploy to Vercel Preview
        id: vercel-deploy
        run: |
          PREVIEW_URL=$(vercel deploy --confirm --token=$VERCEL_TOKEN \
            | grep '^Preview:' | awk '{print $2}')
          echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT

      - name: Comment PR with Preview URL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = github.event.workflow_run.pull_requests[0];
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: `Preview is live: ${{ steps.vercel-deploy.outputs.preview_url }}`
            })
