name: Production Deployment

on:
  workflow_run:
    workflows:
      - Development
    types:
      - completed

permissions:
  contents: read
  deployments: write

env:
  VERCEL_ORG_ID:     ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN:      ${{ secrets.VERCEL_TOKEN }}

jobs:
  Deploy-Production:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    
    environment: production
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token="$VERCEL_TOKEN"

      - name: Build Project Artifacts
        run: vercel build --prod --token="$VERCEL_TOKEN"

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token="$VERCEL_TOKEN"
