name: Production Deployment

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  deployments: write

env:
  VERCEL_ORG_ID:     ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN:      ${{ secrets.VERCEL_TOKEN }}

jobs:
  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest

    environment:
      name: Production
      url: ${{ steps.vercel-deploy.outputs.url }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install --global pnpm@latest

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token="$VERCEL_TOKEN"

      - name: Build Project Artifacts
        run: vercel build --prod --token="$VERCEL_TOKEN"

      - name: Deploy Project Artifacts to Vercel
        id: vercel-deploy
        run: |
          URL=$(vercel deploy --prod --confirm --token=$VERCEL_TOKEN \
            | grep '^Production:' | awk '{print $2}')
          echo "url=$URL" >> $GITHUB_OUTPUT
